// Generated by CoffeeScript 1.10.0
var request = require('request');
var async = require('async');

function Doctor() {
  console.log("Doctor: well, I'm exmaming.");
}

Doctor.prototype.examine = function(data, callback, msg) {
  var options = { url: data.url };
  var message = {};
  request.get(options, function(err, res, body) {
    if (err) {
      message = {
        "status": "error",
        "statusCode": null,
        "discription": "ERROR: \"" + data.url + "\" Connection fail."
      };
      callback(message, msg);
    } else if (res.statusCode === data.status) {
      message = {
        "status": "matched",
        "statusCode": "" + res.statusCode,
        "discription": "SUCCESS: \"" + data.url + "\" has been alive :)"
      };
      callback(message, msg);
    } else if (res.statusCode !== data.status) {
      message = {
        "status": "unmatched",
        "statusCode": "" + res.statusCode,
        "discription": "ERROR: \"" + data.url + "\" [expect]: \"" + data.status + "\", [actual]: \"" + res.statusCode + "\""
      };
      callback(message, msg);
    }
  });
};

module.exports.Doctor = Doctor;
