// Generated by CoffeeScript 1.10.0
var _ = require('lodash');
var Patients = (function() {
    function Patients(robot) {
      this.robot = robot;
      this.key = 'sites';
    }

    Patients.prototype.getData = function() {
      var data, ref;
      data = (ref = robot.brain.get(key)) != null ? ref : [];
      return data;
    };


    /* Remove */

    Patients.prototype.removeSite = function(index) {
      var data, tmp;
      data = this.getData();

      /* エラーチェック(範囲外判定) */
      if (index > (_.size(data) - 1)) {
        return false;
      }

      /* 最後の出力に使う */
      tmp = {
        url: data[index].url,
        status: data[index].status
      };

      /* indexから1つ削除 */
      data.splice(index, 1);
      return tmp;
    };


    /* Update */
    Patients.prototype.updateSite = function(index, newStatus) {
      var data;
      data = this.getData();
      if (index > (_.size(data) - 1)) {
        return false;
      }
      data[index].status = newStatus;
      return true;
    };

    /* index生成 */
    Patients.prototype.searchIndex = function(obj, key) {
      var index, newObj;
      newObj = _.map(obj, 'url');
      index = newObj.indexOf(key);
      if (index > -1) {
        return index;
      } else {
        return false;
      }
    };

    Patients.prototype.checkConfliction = function(obj, key) {
      if (_.findIndex(obj, {
        url: key
      }) > -1) {
        return false;
      } else {
        return true;
      }
    };

    return Patients;

  })();

  module.exports = Patients;
